### ISSUE TITLE
is my MTL file not getting used?

### ISSUE THREAD

**Issue by SagarKhurana** [the3deers/android-3D-model-viewer#101]
Hi @andresoviedo , thank you such a great library to work with OpenGL in android.

I am facing challenges in loading the .obj file with its mtl file. 
I see it in logs that some properties like below:
```
//color info
private Tuple3 ka, kd, ks; // ambient, diffuse, specular colours
private float ns; // shininess
private float d; // alpha
```
are getting extracted from the materials but I suppose they are never used. 

As the below method is never called and commented.

```
public void setMaterialColors(GLES20 gl)
		// start rendering using this material's colour information
		{
//			 if (ka != null) { // ambient color
//			 float[] colorKa = {ka.getX(), ka.getY(), ka.getZ(), 1.0f};
//			 gl.glMaterialfv(GLES20.GL_FRONT_AND_BACK, GLES20.GL_AMBIENT, colorKa, 0);
//			 }
//			 if (kd != null) { // diffuse color
//			 float[] colorKd = {kd.getX(), kd.getY(), kd.getZ(), 1.0f};
//			 gl.glMaterialfv(GLES20.GL_FRONT_AND_BACK, GLES20.GL_DIFFUSE, colorKd, 0);
//			 }
//			 if (ks != null) { // specular color
//			 float[] colorKs = {ks.getX(), ks.getY(), ks.getZ(), 1.0f};
//			 gl.glMaterialfv(GLES20.GL_FRONT_AND_BACK, GLES20.GL_SPECULAR, colorKs, 0);
//			 }
//
//			 if (ns != 0.0f) { // shininess
//			 gl.glMaterialf(GLES20.GL_FRONT_AND_BACK, GLES20.GL_SHININESS, ns);
//			 }
//
//			 if (d != 1.0f) { // alpha
//			 // not implemented
//			 }
		} // end of setMaterialColors()
```
and few properties like Ni and Tf from my mtl file was ignored.
above code resulting in my 3d model is not getting rendered as expected.

It would be great if you can help. 
I want to load my .obj files with its .mtl file. 
Thanks in Advance.

**Comment by andresoviedo** [comment]
Hi.  Yes. Currently only some of the material properties are processed.
Please. Is it possible for you to share the model so I can take a look?
Regards

**Comment by SagarKhurana** [comment]
Hi @andresoviedo, please find the sample 3d model [tea_pot.obj](https://drive.google.com/open?id=1g3ByjDwpALvftoEqc1aNPyat6Isq1fFt) and its .mlt file which is getting rendered in the 3d model viewer but I see in the logs that it is still ignoring some of the material properties. 

Find the log information below for more reference: 

```
I/WavefrontLoader: Number of vertices:2081
I/WavefrontLoader: Number of faces:4032
I/WavefrontLoader: No. of vertices: 2081
I/WavefrontLoader: No. of normal coords: 2082
I/WavefrontLoader: No. of tex coords: 3425
I/WavefrontLoader: No. of faces: 4032
I/System.out: No. of materials used: 0
I/ContentUtils: Opening stream /storage/emulated/0/images/tea_pot.obj
I/Object3DBuilder: Generating arrays for /storage/emulated/0/images/tea_pot.obj
I/Object3DBuilder: Allocating vertex array buffer... Vertices (12096)
I/Object3DBuilder: Populating vertex array...
I/Object3DBuilder: Allocating vertex normals buffer... Total normals (4032)
I/Object3DBuilder: Populating normals buffer...
I/Object3DBuilder: Reading materials...
I/ContentUtils: Opening stream /storage/emulated/0/images/tea_pot.mtl
V/materials: Reading material...
D/Loader: New material found: blinn1SG
**I/System.out: Ignoring MTL line: Tf 1.00 1.00 1.00
I/System.out: Ignoring MTL line: Ni 1.00**
I/WavefrontLoader: No. of materials: 1
I/System.out: blinn1SG
I/System.out:   Ka: ( 0.0, 0.0, 0.0 )
I/System.out:   Kd: ( 1.0, 1.0, 0.0 )
I/System.out:   Ks: ( 1.0, 1.0, 1.0 )
I/Object3DBuilder: Processing face materials...
```

**Comment by shiaro007-joker** [comment]
Hi @andresoviedo  I'm facing this same issue. I tried loading a sample  obj and mtl file placed in the same folder but when the object loaded it had no material or texture. It was just grey? Can you please help?

**Comment by shiaro007-joker** [comment]
Hi @andresoviedo  I was debugging the code and found a comment that states :
_"// check if texture is ok (Because we only support 1 texture currently)"_

Can you please tell why is this so and how can I load an obj that has multiple textures in the mtl??

**Comment by Ram8948** [comment]
i also have same problem any solution?

**Comment by andresoviedo** [comment]
Hi. just checked. latest released version (2.7.0) works fine for me!
I see a yellow teapot and also a teapot with texture, colors and the top brown
If I'm right, this issue is about enhancing color properties like Ni or Tf.

**Comment by IBelieves** [comment]
MTL has multiple textures, how to deal with it?

**Comment by andresoviedo** [comment]
Hello @IBelieves 
I recently released a new version of the app
that shoud solve most texture issues, so I will close this for now
please give it a try
kind regards
