### ISSUE TITLE
Is there any way to render an image as background?

### ISSUE THREAD

**Issue by Nero9Chan** [the3deers/android-3D-model-viewer#142]
I am trying to render an image as background instead of just using background color. What I am trying to do is render background image and 3d model on the same screen. Is it possible to achieve? If yes, could you provide me some tips?

**Comment by andresoviedo** [comment]
good question :)

**Comment by andresoviedo** [comment]
Hello @Nero9Chan I did some research.

1 strategy is using a Sky Box.  
There is a nice tutorial here: https://learnopengl.com/Advanced-OpenGL/Cubemaps

I am indeed preparing a new release with a new feature 
to toggle between different backgrounds, including a Sky Box containing 6 textures.

I'll do my best to release it soon  Regards

**Comment by andresoviedo** [comment]
hi. i implemented a skybox to be able to render a 3D image in the background
I commited all the code to master branch. Soon I will release to google play.
Regards
