### ISSUE TITLE
E/MeshData: Wrong normal index: -1

### ISSUE THREAD

**Issue by houtian80** [the3deers/android-3D-model-viewer#147]
My model give a error code 
E/MeshData: Wrong normal index: -1

**Comment by houtian80** [comment]
hi
this is my model, I load this file but load error
[22.zip](https://github.com/the3deers/android-3D-model-viewer/files/5273458/22.zip)

**Comment by houtian80** [comment]
1、贴片没有加载处理
2、动画加载也有问题

**Comment by andresoviedo** [comment]
Hi 
I think I fixed it.  You see it ok now ?
I think she is cute :1st_place_medal: 

![22](https://user-images.githubusercontent.com/1988725/94943803-8ffb7300-04d8-11eb-998d-0b84de07ea38.gif)

**Comment by houtian80** [comment]
thank you very much!!!
but I have another problem，
when I load this model  with texture ，it doesn't work
what can i do next？

**Comment by andresoviedo** [comment]
hi @houtian80 
please check the texture has relative path in the xml
you have cowboy.dae as an example.
regards

**Comment by houtian80** [comment]
> hi @houtian80
> please check the texture has relative path in the xml
> you have cowboy.dae as an example.
> regards

I tried, and it still doesn't work

**Comment by houtian80** [comment]
> hi @houtian80
> please check the texture has relative path in the xml
> you have cowboy.dae as an example.
> regards

[Uploading IMG_4208.MOV.zip…]()

**Comment by houtian80** [comment]
> hi @houtian80
> please check the texture has relative path in the xml
> you have cowboy.dae as an example.
> regards

[IMG_4208.MOV.zip](https://github.com/the3deers/android-3D-model-viewer/files/5338239/IMG_4208.MOV.zip)
