### ISSUE TITLE
How can i show custom image ?

### ISSUE THREAD

**Issue by rohitTechStone** [the3deers/android-3D-model-viewer#149]
Hello 
I want to show a custom image of how can I achieve  please help me out

**Comment by andresoviedo** [comment]
Hello @rohitTechStone 
How do you want to render the image? 
Do you want to change the texture?

**Comment by rohitTechStone** [comment]
hello @andresoviedo 
yes I have an image URL I want to render the URL image into the view it is posible

**Comment by andresoviedo** [comment]
hello @rohitTechStone 
if you want to load an image in the OpenGL 3D canvas you can do it by loading a texture using a URI a a parameter.
Then you can bind that texture to the object. The object needs texture coordinates.
You have an example in the app on "menu -> samples -> cube"

Is that what you want to achieve or you want something else?

Regards
