### ISSUE TITLE
Fps view bug.

### ISSUE THREAD

**Issue by Dextergithubb** [the3deers/android-3D-model-viewer#156]
Fps draw
![Screenshot_20201112-113022372](https://user-images.githubusercontent.com/74251431/98888084-95d27400-24da-11eb-8309-240789855852.jpg)
 twice when i choose load texture.

**Comment by andresoviedo** [comment]
I know. Lol
It's already fixed in my local
Ill push it soon
Thanks.

**Comment by Dextergithubb** [comment]
Ok
