### ISSUE TITLE
加载模型只能显示一张图片效果

### ISSUE THREAD

**Issue by zekoushenhao** [the3deers/android-3D-model-viewer#175]
obj->mtl->的时候需要加载多张图片渲染效果，选择多张图片后实际效果只有一张图片的

**Comment by 17601614169** [comment]
What engine is used to interpret the DAE model? Is this engine suitable for IOS and PC?

**Comment by IBelieves** [comment]
> 

你好，后来怎么处理的？改造GLUtil?

**Comment by IBelieves** [comment]
@zekoushenhao 你好，请问后面你怎么处理的？mtl存在多张纹理，需要一次load all

**Comment by andresoviedo** [comment]
closing due to unclear request
please use **english** as much as possible
kind regards
