### ISSUE TITLE
How can I make a 3d object smooth?

### ISSUE THREAD

**Issue by mosvict** [the3deers/android-3D-model-viewer#192]
Hello. 
How can I make a 3d object smooth?
Please help me.
There is a way to solve in iOS.
object.addNormals(withAttributeNamed: MDLVertexAttributeNormal, creaseThreshold: 0)
How can I make a 3d object smooth using android-3D-model-view in android?

**Comment by andresoviedo** [comment]
Hello buddy
I released a new version where I fixed the smooth feature. 
Please give it a try
If you still experience issues, please let me know.
Kind regards
