### ISSUE TITLE
How to add Multiple STL files in a model

### ISSUE THREAD

**Issue by umer-aprevoapp** [the3deers/android-3D-model-viewer#198]
I am trying to face problem for adding and removing stl files from a model.
What I want to achieve is :
Add Multiple STL models in a mesh
can able to remove an STL model on selecting.
please help to update the code and mention here
What I want is referring to this app below:
https://play.google.com/store/apps/details?id=com.performance.meshview

**Comment by andresoviedo** [comment]
Dear @umer-aprevoapp 
Sorry for the late reply

You could take a look to the Demo loading example. That example adds multiple Objects to the 3D world

You could take a look also to the SceneLoader where there is a callback whenever some object is selected
There you could delete the Object from the list

Hope that helps
Kind regards
