### ISSUE TITLE
How to add text to Object3DData ??

### ISSUE THREAD

**Issue by quangdparis** [the3deers/android-3D-model-viewer#203]
Hello, Thank you for sharing

I want to ask how to add text to Object3DData

If you know how to do, please answer me, thank you very much

**Comment by andresoviedo** [comment]
Hello @quangdparis 
sorry for the late reply

If you want to add text 1 option could be rendering your text inside a textured image
Then you can attach that texture to the model, plane or whatever you want.

Kind regards
