### ISSUE TITLE
Textures not rendered correctly ?   obj模型 贴图问题

### ISSUE THREAD

**Issue by Destroyer716** [the3deers/android-3D-model-viewer#204]
您好：
有些obj模型加载的时候，贴图有些问题，
正常加载如下图：
![微信图片_20220413190803](https://user-images.githubusercontent.com/25731175/163167740-5a42bb4b-4765-45d3-b7bf-113d57984bfc.png)
使用这个项目加载如下图：
![微信图片_20220413191030](https://user-images.githubusercontent.com/25731175/163168048-46f1b54b-e4d2-45e2-97eb-154be1abbec1.jpg)
边框应该是没有贴图的。
感谢

**Comment by Destroyer716** [comment]
这是我使用的obj 模型
[1.zip](https://github.com/the3deers/android-3D-model-viewer/files/8480939/1.zip)

**Comment by Destroyer716** [comment]
还有一个模型显示也有问题
正常的应该是下面这样
![image](https://user-images.githubusercontent.com/25731175/163305476-bbfca485-99bc-485e-b485-2fc132caf121.png)
但是在此项目中却是这样的，请注意我箭头指向的部分
![image](https://user-images.githubusercontent.com/25731175/163305613-20ec442a-0bcc-45c1-9ed4-3638bac62381.png)
请问我该如何处理

**Comment by Destroyer716** [comment]
这是obj文
[satellite.zip](https://github.com/the3deers/android-3D-model-viewer/files/8486109/satellite.zip)
件

**Comment by andresoviedo** [comment]
Hello @Destroyer716 
Thank you for your feedback
I will take a look 

Many thanks

**Comment by andresoviedo** [comment]
Hello @Destroyer716 
I think your examples work fine on the latest version 
please have a look
regards
