### ISSUE TITLE
Feeding camera frame as background scene

### ISSUE THREAD

**Issue by rag3456** [the3deers/android-3D-model-viewer#205]
Hello everyone,

I am new to android. 

In c++ I have rendered the 3d obj file  on live camera feed. How can I do the same thing here using this library?

Please somebody who know that give me an idea on how to do that. Thanks..

**Comment by andresoviedo** [comment]
Duplicated of #170

**Comment by ducanh3005** [comment]
Can you share for me your way rendered the 3D obj file in C++ @rag3456 my email ynsuperit@gmail.com
