### ISSUE TITLE
How to control the camera to move to a fixed angle

### ISSUE THREAD

**Issue by LuoGuoXin** [the3deers/android-3D-model-viewer#206]
I want to control the camera to move to a certain angle, instead of the angle stacking, how to deal with it? Because I want to move exactly to a fixed angle

**Comment by SkyEric** [comment]
> I want to control the camera to move to a certain angle, instead of the angle stacking, how to deal with it? Because I want to move exactly to a fixed angle

@LuoGuoXin can you fix this problem? I also have the same problem

**Comment by andresoviedo** [comment]
Hello there.
Latest version allows you to configure a free camera orientation and location.
Please give it a try
