### ISSUE TITLE
When you can add gltf supported

### ISSUE THREAD

**Issue by ranashahidbashir** [the3deers/android-3D-model-viewer#213]
Hi,
When can gltf be supported

**Comment by andresoviedo** [comment]
hey. good question
i just found someone did something already ;)
https://github.com/WenlinMao/android-3d-model-viewer

**Comment by ranashahidbashir** [comment]
Hey, @andresoviedo thanks for your message. 

I used the above library but I found some issues in it and some features are still missing. it's not been updated for the last 3 years. 

Can you add the missing feature in https://github.com/WenlinMao/android-3d-model-viewer?

**Comment by andresoviedo** [comment]
Hello @ranashahidbashir 
Thank for the feedback

I will check that
Not sure how long it will take
I will start working on that

Regards

**Comment by ranashahidbashir** [comment]
Hey @andresoviedo 
Thanks for your assistance.
I am looking forward to the next update.

Thanks

**Comment by andresoviedo** [comment]
duplicate of #176

**Comment by andresoviedo** [comment]
Hello @ranashahidbashir 
i just commited a fix to support gltf basic features
please give it a try
regards

**Comment by ranashahidbashir** [comment]
Hey @andresoviedo 
Thank you for adding GlTF Support, yes, I check it's working well for the GLTF file. if I found any issues in the future then I update you.

Thanks
