### ISSUE TITLE
load more texture,

### ISSUE THREAD

**Issue by IBelieves** [the3deers/android-3D-model-viewer#214]
The current example can only load a single texture, how to load all at once. I tried loop binding them all and only the first texture worked

**Comment by IBelieves** [comment]
[Obj2.zip](https://github.com/the3deers/android-3D-model-viewer/files/9535574/Obj2.zip)
这是多个纹理的模型

**Comment by andresoviedo** [comment]
Thank you  @IBelieves 
I will fix that asap
Regards

**Comment by IBelieves** [comment]
thanks @andresoviedo Looking forward to repair

**Comment by andresoviedo** [comment]
for the record

https://github.com/the3deers/android-3D-model-viewer/blob/571ef43de7ec03944e579558cfc2e913e6216ccb/engine/src/main/java/org/andresoviedo/android_3d_model_engine/drawer/GLES20Renderer.java#L428

**Comment by IBelieves** [comment]
[obj_model.zip](https://github.com/the3deers/android-3D-model-viewer/files/9541676/obj_model.zip)
Nope, with my model you can see that I have 6 normal textures in my model, ideally render them all at once, but only one actually works @andresoviedo

**Comment by andresoviedo** [comment]
hello @IBelieves 
i just commited a fix to correctly load the watch (master branch)
please give it a try
regards
